name: Test

on:
  push:
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: '22.22.3'

      - name: Setup Pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Get Pnpm Store Directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v6
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install
        run: cd extensions/frontstore_bundle && pnpm install --no-frozen-lockfile

      - name: Typecheck
        run: cd extensions/frontstore_bundle && pnpm test
